#ifndef DEFAULTHEADERDECLARATION_H
#define DEFAULTHEADERDECLARATION_H

/**
    The defualt header declaration.
*/

/************************************************************************************
**
**  Copyright (c) 2019 VCLHG. All rights reserved.
**
**  File   : DefaultHeaderDeclaration.h
**  Author : VCLHG
**  Date   : 2020-01-10T00:21::30
**
**         Generated by VCLHG.
**
************************************************************************************/

static const char* defaultHeaderDeclaration =
    "/************************************************************************************ \n"
    "**                                                                                    \n"
    "**  Copyright (c) $[DATE(YYYY)] . All rights reserved.                                \n"
    "**                                                                                    \n"
    "**  File   : $[FILE_NAME]                                                             \n"
    "**  Author : $[AUTHOR]                                                                \n"
    "**  Date   : $[DATE_TIME(YYYY-MM-ddThh:mm::ss)]                                       \n"
    "**                                                                                    \n"
    "**         Generated by VCLHG.                                                        \n"
    "**                                                                                    \n"
    "************************************************************************************/ \n"
    ;

#endif // DEFAULTHEADERDECLARATION_H
